name = "hardmode"
version = "1.0.0"

description = "A backend monolith for Genseng Hardmode"
licences = ["MIT"]
repository = { type = "github", user = "genseng", repo = "hardmode" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
wisp = ">= 1.8.0 and < 2.0.0"
mist = ">= 5.0.1 and < 6.0.0"
gleam_erlang = ">= 1.2.0 and < 2.0.0"
gleam_http = ">= 4.0.0 and < 5.0.0"
gleam_json = ">= 3.0.2 and < 4.0.0"
gleam_time = ">= 1.2.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
